"""add_multitenant_support

Revision ID: d2d7f0966055
Revises: cba93d2c83f1
Create Date: 2026-01-12 10:05:46.844990+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2d7f0966055'
down_revision: Union[str, Sequence[str], None] = 'cba93d2c83f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_OWNER', 'PLATFORM_ADMIN', 'PLATFORM_SUPPORT', 'PLATFORM_SALES', name='super_admin_role_enum', create_constraint=True), nullable=False),
    sa.Column('mfa_secret', sa.String(length=500), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_backup_codes', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Administrateurs de la plateforme CareLink (équipe interne)'
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_table('platform_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('super_admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_tenant_id', sa.Integer(), nullable=True),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment="Logs d'audit des actions super-admin (immuables)"
    )
    op.create_index(op.f('ix_platform_audit_logs_action'), 'platform_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_created_at'), 'platform_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_request_id'), 'platform_audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_super_admin_id'), 'platform_audit_logs', ['super_admin_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_target_tenant_id'), 'platform_audit_logs', ['target_tenant_id'], unique=False)
    op.create_table('user_tenant_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_by_super_admin_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_super_admin_id'], ['super_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'is_active', name='uq_user_tenant_active'),
    comment="Rattachements d'utilisateurs à des tenants supplémentaires (cross-tenant)"
    )
    op.create_index('ix_user_tenant_assignments_active', 'user_tenant_assignments', ['is_active', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_user_tenant_assignments_is_active'), 'user_tenant_assignments', ['is_active'], unique=False)
    op.create_index('ix_user_tenant_assignments_tenant', 'user_tenant_assignments', ['tenant_id'], unique=False)
    op.create_index('ix_user_tenant_assignments_user', 'user_tenant_assignments', ['user_id'], unique=False)
    op.add_column('care_plan_services', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_care_plan_services_tenant_id'), 'care_plan_services', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'care_plan_services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('care_plans', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_care_plans_tenant_id'), 'care_plans', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'care_plans', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('coordination_entries', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_coordination_entries_tenant_id'), 'coordination_entries', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'coordination_entries', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('entity_services', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_entity_services_tenant_id'), 'entity_services', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'entity_services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_access', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_patient_access_tenant_id'), 'patient_access', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patient_access', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_devices', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_patient_devices_tenant_id'), 'patient_devices', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patient_devices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_documents', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_patient_documents_tenant_id'), 'patient_documents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patient_documents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_evaluations', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_patient_evaluations_tenant_id'), 'patient_evaluations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patient_evaluations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_thresholds', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_patient_thresholds_tenant_id'), 'patient_thresholds', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patient_thresholds', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('patient_vitals', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_patient_vitals_tenant_id'), 'patient_vitals', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'patient_vitals', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('scheduled_interventions', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_scheduled_interventions_tenant_id'), 'scheduled_interventions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_interventions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_availabilities', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_user_availabilities_tenant_id'), 'user_availabilities', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_availabilities', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_entities', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_user_entities_tenant_id'), 'user_entities', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_entities', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_roles', sa.Column('tenant_id', sa.Integer(), nullable=False, comment='Tenant propriétaire de cet enregistrement'))
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    # op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.create_foreign_key(None, 'user_roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    # op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_column('user_roles', 'tenant_id')
    op.drop_constraint(None, 'user_entities', type_='foreignkey')
    op.drop_index(op.f('ix_user_entities_tenant_id'), table_name='user_entities')
    op.drop_column('user_entities', 'tenant_id')
    op.drop_constraint(None, 'user_availabilities', type_='foreignkey')
    op.drop_index(op.f('ix_user_availabilities_tenant_id'), table_name='user_availabilities')
    op.drop_column('user_availabilities', 'tenant_id')
    op.drop_constraint(None, 'scheduled_interventions', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_interventions_tenant_id'), table_name='scheduled_interventions')
    op.drop_column('scheduled_interventions', 'tenant_id')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_column('roles', 'tenant_id')
    op.drop_constraint(None, 'patient_vitals', type_='foreignkey')
    op.drop_index(op.f('ix_patient_vitals_tenant_id'), table_name='patient_vitals')
    op.drop_column('patient_vitals', 'tenant_id')
    op.drop_constraint(None, 'patient_thresholds', type_='foreignkey')
    op.drop_index(op.f('ix_patient_thresholds_tenant_id'), table_name='patient_thresholds')
    op.drop_column('patient_thresholds', 'tenant_id')
    op.drop_constraint(None, 'patient_evaluations', type_='foreignkey')
    op.drop_index(op.f('ix_patient_evaluations_tenant_id'), table_name='patient_evaluations')
    op.drop_column('patient_evaluations', 'tenant_id')
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.drop_index(op.f('ix_patient_documents_tenant_id'), table_name='patient_documents')
    op.drop_column('patient_documents', 'tenant_id')
    op.drop_constraint(None, 'patient_devices', type_='foreignkey')
    op.drop_index(op.f('ix_patient_devices_tenant_id'), table_name='patient_devices')
    op.drop_column('patient_devices', 'tenant_id')
    op.drop_constraint(None, 'patient_access', type_='foreignkey')
    op.drop_index(op.f('ix_patient_access_tenant_id'), table_name='patient_access')
    op.drop_column('patient_access', 'tenant_id')
    op.drop_constraint(None, 'entity_services', type_='foreignkey')
    op.drop_index(op.f('ix_entity_services_tenant_id'), table_name='entity_services')
    op.drop_column('entity_services', 'tenant_id')
    op.drop_constraint(None, 'coordination_entries', type_='foreignkey')
    op.drop_index(op.f('ix_coordination_entries_tenant_id'), table_name='coordination_entries')
    op.drop_column('coordination_entries', 'tenant_id')
    op.drop_constraint(None, 'care_plans', type_='foreignkey')
    op.drop_index(op.f('ix_care_plans_tenant_id'), table_name='care_plans')
    op.drop_column('care_plans', 'tenant_id')
    op.drop_constraint(None, 'care_plan_services', type_='foreignkey')
    op.drop_index(op.f('ix_care_plan_services_tenant_id'), table_name='care_plan_services')
    op.drop_column('care_plan_services', 'tenant_id')
    op.drop_index('ix_user_tenant_assignments_user', table_name='user_tenant_assignments')
    op.drop_index('ix_user_tenant_assignments_tenant', table_name='user_tenant_assignments')
    op.drop_index(op.f('ix_user_tenant_assignments_is_active'), table_name='user_tenant_assignments')
    op.drop_index('ix_user_tenant_assignments_active', table_name='user_tenant_assignments')
    op.drop_table('user_tenant_assignments')
    op.drop_index(op.f('ix_platform_audit_logs_target_tenant_id'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_super_admin_id'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_request_id'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_created_at'), table_name='platform_audit_logs')
    op.drop_index(op.f('ix_platform_audit_logs_action'), table_name='platform_audit_logs')
    op.drop_table('platform_audit_logs')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    # ### end Alembic commands ###
