"""initial_schema_v4_1_with_multitenant

Revision ID: cba93d2c83f1
Revises: 
Create Date: 2026-01-05 10:02:31.294195+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba93d2c83f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code'),
    comment='Table des pays où CareLink est déployé'
    )
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('requires_rpps', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    comment='Table des professions de santé réglementées'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Table des rôles fonctionnels avec leurs permissions'
    )
    op.create_table('service_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('SOINS', 'HYGIENE', 'REPAS', 'MOBILITE', 'COURSES', 'MENAGE', 'ADMINISTRATIF', 'SOCIAL', 'AUTRE', name='service_category_enum', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_profession_id', sa.Integer(), nullable=True),
    sa.Column('required_qualification', sa.String(length=100), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('is_medical_act', sa.Boolean(), nullable=False),
    sa.Column('apa_eligible', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['required_profession_id'], ['professions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Catalogue national des types de prestations'
    )
    op.create_index(op.f('ix_service_templates_category'), 'service_templates', ['category'], unique=False)
    op.create_index(op.f('ix_service_templates_code'), 'service_templates', ['code'], unique=True)
    op.create_index(op.f('ix_service_templates_required_profession_id'), 'service_templates', ['required_profession_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Code unique du tenant (ex: GCSMS-BV-IDF)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nom commercial'),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='Raison sociale officielle'),
    sa.Column('siret', sa.String(length=14), nullable=True, comment='Numéro SIRET (France)'),
    sa.Column('tenant_type', sa.Enum('GCSMS', 'SSIAD', 'SAAD', 'SPASAD', 'EHPAD', 'DAC', 'CPTS', 'OTHER', name='tenant_type_enum', create_constraint=True), nullable=False, comment='Type de structure principale'),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', name='tenant_status_enum', create_constraint=True), nullable=False, comment='Statut du tenant'),
    sa.Column('contact_email', sa.String(length=255), nullable=False, comment='Email du contact principal'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Téléphone du contact principal'),
    sa.Column('billing_email', sa.String(length=255), nullable=True, comment='Email pour la facturation (si différent)'),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True, comment='Pays du tenant'),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=False, comment='Référence vers la clé AES dans le vault'),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=True, comment='Limite contractuelle de patients (NULL = illimité)'),
    sa.Column('max_users', sa.Integer(), nullable=True, comment="Limite contractuelle d'utilisateurs (NULL = illimité)"),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False, comment='Quota de stockage en Go'),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Paramètres personnalisés du tenant (JSON)'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='Date de mise en service'),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True, comment='Date de résiliation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.Enum('SSIAD', 'SAAD', 'SAD', 'SPASAD', 'SAP', 'EHPAD', 'RESIDENCE_AUTONOMIE', 'ACCUEIL_JOUR', 'FAM', 'MAS', 'SESSAD', 'IME', 'ESAT', 'GCSMS', 'DAC', 'CPTS', 'PCPE', 'PCO', 'HOSPITAL', 'CLINIC', 'CSI', 'HAD', 'HALTE_REPIT', 'FORMATION', 'OTHER', name='entity_type_enum', create_constraint=True), nullable=False),
    sa.Column('integration_type', sa.Enum('MANAGED', 'FEDERATED', 'CONVENTION', 'FINANCIAL_CONTROL', name='integration_type_enum', create_constraint=True), nullable=True),
    sa.Column('parent_entity_id', sa.Integer(), nullable=True),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('siren', sa.String(length=9), nullable=True),
    sa.Column('finess_ej', sa.String(length=9), nullable=True),
    sa.Column('finess_et', sa.String(length=9), nullable=True),
    sa.Column('authorized_capacity', sa.Integer(), nullable=True),
    sa.Column('authorization_date', sa.Date(), nullable=True),
    sa.Column('authorization_reference', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Latitude du siège'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Longitude du siège'),
    sa.Column('default_intervention_radius_km', sa.Integer(), nullable=True, comment="Rayon d'intervention par défaut en km"),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finess_et'),
    sa.UniqueConstraint('siret'),
    comment='Table des entités de soins (SSIAD, EHPAD, SAAD...)'
    )
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.Enum('S', 'M', 'L', 'XL', 'ENTERPRISE', name='subscription_plan_enum', create_constraint=True), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscription_status_enum', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('trial_ends_at', sa.Date(), nullable=True),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('price_per_extra_patient_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billing_cycle_enum', create_constraint=True), nullable=False),
    sa.Column('included_patients', sa.Integer(), nullable=False),
    sa.Column('included_users', sa.Integer(), nullable=True),
    sa.Column('included_storage_gb', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Abonnements et facturation des tenants'
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('rpps', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table des utilisateurs (professionnels de santé et administratifs)'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_rpps'), 'users', ['rpps'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('entity_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('service_template_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('price_euros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_capacity_week', sa.Integer(), nullable=True),
    sa.Column('custom_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_template_id'], ['service_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'service_template_id', name='uq_entity_service'),
    comment='Services proposés par chaque entité'
    )
    op.create_index(op.f('ix_entity_services_entity_id'), 'entity_services', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_services_service_template_id'), 'entity_services', ['service_template_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nir_encrypted', sa.String(length=500), nullable=True),
    sa.Column('ins_encrypted', sa.String(length=500), nullable=True),
    sa.Column('first_name_encrypted', sa.String(length=500), nullable=True),
    sa.Column('last_name_encrypted', sa.String(length=500), nullable=True),
    sa.Column('birth_date_encrypted', sa.String(length=500), nullable=True),
    sa.Column('address_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('phone_encrypted', sa.String(length=500), nullable=True),
    sa.Column('email_encrypted', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('medecin_traitant_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Latitude du domicile (précision réduite pour RGPD)'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Longitude du domicile (précision réduite pour RGPD)'),
    sa.Column('geo_validated_at', sa.DateTime(), nullable=True, comment='Date de dernière validation de la géolocalisation'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['medecin_traitant_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table des patients (données chiffrées AES-256-GCM)'
    )
    op.create_index(op.f('ix_patients_entity_id'), 'patients', ['entity_id'], unique=False)
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_table('subscription_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('active_patients_count', sa.Integer(), nullable=False),
    sa.Column('active_users_count', sa.Integer(), nullable=False),
    sa.Column('storage_used_mb', sa.Integer(), nullable=False),
    sa.Column('api_calls_count', sa.Integer(), nullable=False),
    sa.Column('base_amount_cents', sa.Integer(), nullable=True),
    sa.Column('overage_amount_cents', sa.Integer(), nullable=False),
    sa.Column('total_amount_cents', sa.Integer(), nullable=True),
    sa.Column('invoiced', sa.Boolean(), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'period_start', name='uq_subscription_usage_period'),
    comment='Suivi de consommation mensuelle des abonnements'
    )
    op.create_index(op.f('ix_subscription_usage_subscription_id'), 'subscription_usage', ['subscription_id'], unique=False)
    op.create_table('user_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('max_patients', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('day_of_week >= 1 AND day_of_week <= 7', name='ck_user_avail_day_of_week'),
    sa.CheckConstraint('start_time < end_time', name='ck_user_avail_time_range'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Disponibilités récurrentes des professionnels'
    )
    op.create_index(op.f('ix_user_availabilities_day_of_week'), 'user_availabilities', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_user_availabilities_entity_id'), 'user_availabilities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_availabilities_user_id'), 'user_availabilities', ['user_id'], unique=False)
    op.create_table('user_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('intervention_radius_km', sa.Integer(), nullable=True, comment="Rayon d'intervention personnalisé en km (NULL = défaut entité)"),
    sa.Column('max_daily_patients', sa.Integer(), nullable=True, comment='Nombre max de patients par jour'),
    sa.Column('max_weekly_hours', sa.Integer(), nullable=True, comment='Heures max par semaine'),
    sa.Column('default_start_time', sa.Time(), nullable=True, comment='Heure de début par défaut'),
    sa.Column('default_end_time', sa.Time(), nullable=True, comment='Heure de fin par défaut'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_id', name='uq_user_entity'),
    comment='Table de jonction User ↔ Entity (many-to-many)'
    )
    op.create_index(op.f('ix_user_entities_entity_id'), 'user_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_entities_user_id'), 'user_entities', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
    comment='Table de jonction User ↔ Role (many-to-many)'
    )
    op.create_table('coordination_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('intervention_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('next_actions', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Carnet de coordination des interventions'
    )
    op.create_index(op.f('ix_coordination_entries_category'), 'coordination_entries', ['category'], unique=False)
    op.create_index(op.f('ix_coordination_entries_patient_id'), 'coordination_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_coordination_entries_performed_at'), 'coordination_entries', ['performed_at'], unique=False)
    op.create_index(op.f('ix_coordination_entries_user_id'), 'coordination_entries', ['user_id'], unique=False)
    op.create_table('patient_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table de traçabilité des accès patients (RGPD)'
    )
    op.create_index(op.f('ix_patient_access_patient_id'), 'patient_access', ['patient_id'], unique=False)
    op.create_index('ix_patient_access_patient_user', 'patient_access', ['patient_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_patient_access_user_id'), 'patient_access', ['user_id'], unique=False)
    op.create_table('patient_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=30), nullable=False),
    sa.Column('device_identifier', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('api_credentials_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_type', 'device_identifier', name='uq_device_type_identifier'),
    comment='Table des devices connectés des patients'
    )
    op.create_index('ix_patient_devices_patient', 'patient_devices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_devices_patient_id'), 'patient_devices', ['patient_id'], unique=False)
    op.create_table('patient_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('schema_type', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('evaluation_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gir_score', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table des évaluations patients (JSON Schema)'
    )
    op.create_index(op.f('ix_patient_evaluations_patient_id'), 'patient_evaluations', ['patient_id'], unique=False)
    op.create_table('patient_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vital_type', sa.String(length=20), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('surveillance_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'vital_type', name='uq_patient_vital_type'),
    comment='Table des seuils personnalisés de constantes vitales'
    )
    op.create_index(op.f('ix_patient_thresholds_patient_id'), 'patient_thresholds', ['patient_id'], unique=False)
    op.create_table('care_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('source_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_VALIDATION', 'ACTIVE', 'SUSPENDED', 'COMPLETED', 'CANCELLED', name='care_plan_status_enum', create_constraint=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_hours_week', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gir_at_creation', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evaluation_id'], ['patient_evaluations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number'),
    comment="Plans d'aide patients"
    )
    op.create_index(op.f('ix_care_plans_entity_id'), 'care_plans', ['entity_id'], unique=False)
    op.create_index(op.f('ix_care_plans_patient_id'), 'care_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_plans_source_evaluation_id'), 'care_plans', ['source_evaluation_id'], unique=False)
    op.create_index(op.f('ix_care_plans_status'), 'care_plans', ['status'], unique=False)
    op.create_table('patient_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('generation_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evaluation_id'], ['patient_evaluations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Documents générés pour les patients (PPA, PPCS, Recommandations)'
    )
    op.create_index(op.f('ix_patient_documents_document_type'), 'patient_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_patient_documents_patient_id'), 'patient_documents', ['patient_id'], unique=False)
    op.create_table('patient_vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vital_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['patient_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Table des mesures de constantes vitales'
    )
    op.create_index(op.f('ix_patient_vitals_measured_at'), 'patient_vitals', ['measured_at'], unique=False)
    op.create_index(op.f('ix_patient_vitals_patient_id'), 'patient_vitals', ['patient_id'], unique=False)
    op.create_index('ix_patient_vitals_patient_type_date', 'patient_vitals', ['patient_id', 'vital_type', 'measured_at'], unique=False)
    op.create_table('care_plan_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_id', sa.Integer(), nullable=False),
    sa.Column('service_template_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_week', sa.Integer(), nullable=False),
    sa.Column('frequency_type', sa.Enum('DAILY', 'WEEKLY', 'SPECIFIC_DAYS', 'MONTHLY', 'ON_DEMAND', name='frequency_type_enum', create_constraint=True), nullable=False),
    sa.Column('frequency_days', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('preferred_time_start', sa.Time(), nullable=True),
    sa.Column('preferred_time_end', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='service_priority_enum', create_constraint=True), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('assignment_status', sa.Enum('UNASSIGNED', 'PENDING', 'ASSIGNED', 'CONFIRMED', 'REJECTED', name='assignment_status_enum', create_constraint=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['care_plan_id'], ['care_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_template_id'], ['service_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment="Services individuels des plans d'aide"
    )
    op.create_index(op.f('ix_care_plan_services_assigned_user_id'), 'care_plan_services', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_care_plan_services_assignment_status'), 'care_plan_services', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_care_plan_services_care_plan_id'), 'care_plan_services', ['care_plan_id'], unique=False)
    op.create_index(op.f('ix_care_plan_services_service_template_id'), 'care_plan_services', ['service_template_id'], unique=False)
    op.create_table('scheduled_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_plan_service_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start_time', sa.Time(), nullable=False),
    sa.Column('scheduled_end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'MISSED', 'RESCHEDULED', name='intervention_status_enum', create_constraint=True), nullable=False),
    sa.Column('actual_start_time', sa.Time(), nullable=True),
    sa.Column('actual_end_time', sa.Time(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('coordination_entry_id', sa.Integer(), nullable=True),
    sa.Column('rescheduled_from_id', sa.Integer(), nullable=True),
    sa.Column('rescheduled_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['care_plan_service_id'], ['care_plan_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coordination_entry_id'], ['coordination_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['scheduled_interventions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rescheduled_to_id'], ['scheduled_interventions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Planning des interventions futures'
    )
    op.create_index('ix_sched_interv_date_status', 'scheduled_interventions', ['scheduled_date', 'status'], unique=False)
    op.create_index('ix_sched_interv_patient_date', 'scheduled_interventions', ['patient_id', 'scheduled_date'], unique=False)
    op.create_index('ix_sched_interv_user_date', 'scheduled_interventions', ['user_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_scheduled_interventions_care_plan_service_id'), 'scheduled_interventions', ['care_plan_service_id'], unique=False)
    op.create_index(op.f('ix_scheduled_interventions_coordination_entry_id'), 'scheduled_interventions', ['coordination_entry_id'], unique=False)
    op.create_index(op.f('ix_scheduled_interventions_patient_id'), 'scheduled_interventions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_scheduled_interventions_scheduled_date'), 'scheduled_interventions', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_scheduled_interventions_status'), 'scheduled_interventions', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_interventions_user_id'), 'scheduled_interventions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_interventions_user_id'), table_name='scheduled_interventions')
    op.drop_index(op.f('ix_scheduled_interventions_status'), table_name='scheduled_interventions')
    op.drop_index(op.f('ix_scheduled_interventions_scheduled_date'), table_name='scheduled_interventions')
    op.drop_index(op.f('ix_scheduled_interventions_patient_id'), table_name='scheduled_interventions')
    op.drop_index(op.f('ix_scheduled_interventions_coordination_entry_id'), table_name='scheduled_interventions')
    op.drop_index(op.f('ix_scheduled_interventions_care_plan_service_id'), table_name='scheduled_interventions')
    op.drop_index('ix_sched_interv_user_date', table_name='scheduled_interventions')
    op.drop_index('ix_sched_interv_patient_date', table_name='scheduled_interventions')
    op.drop_index('ix_sched_interv_date_status', table_name='scheduled_interventions')
    op.drop_table('scheduled_interventions')
    op.drop_index(op.f('ix_care_plan_services_service_template_id'), table_name='care_plan_services')
    op.drop_index(op.f('ix_care_plan_services_care_plan_id'), table_name='care_plan_services')
    op.drop_index(op.f('ix_care_plan_services_assignment_status'), table_name='care_plan_services')
    op.drop_index(op.f('ix_care_plan_services_assigned_user_id'), table_name='care_plan_services')
    op.drop_table('care_plan_services')
    op.drop_index('ix_patient_vitals_patient_type_date', table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_patient_id'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_measured_at'), table_name='patient_vitals')
    op.drop_table('patient_vitals')
    op.drop_index(op.f('ix_patient_documents_patient_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_document_type'), table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_index(op.f('ix_care_plans_status'), table_name='care_plans')
    op.drop_index(op.f('ix_care_plans_source_evaluation_id'), table_name='care_plans')
    op.drop_index(op.f('ix_care_plans_patient_id'), table_name='care_plans')
    op.drop_index(op.f('ix_care_plans_entity_id'), table_name='care_plans')
    op.drop_table('care_plans')
    op.drop_index(op.f('ix_patient_thresholds_patient_id'), table_name='patient_thresholds')
    op.drop_table('patient_thresholds')
    op.drop_index(op.f('ix_patient_evaluations_patient_id'), table_name='patient_evaluations')
    op.drop_table('patient_evaluations')
    op.drop_index(op.f('ix_patient_devices_patient_id'), table_name='patient_devices')
    op.drop_index('ix_patient_devices_patient', table_name='patient_devices')
    op.drop_table('patient_devices')
    op.drop_index(op.f('ix_patient_access_user_id'), table_name='patient_access')
    op.drop_index('ix_patient_access_patient_user', table_name='patient_access')
    op.drop_index(op.f('ix_patient_access_patient_id'), table_name='patient_access')
    op.drop_table('patient_access')
    op.drop_index(op.f('ix_coordination_entries_user_id'), table_name='coordination_entries')
    op.drop_index(op.f('ix_coordination_entries_performed_at'), table_name='coordination_entries')
    op.drop_index(op.f('ix_coordination_entries_patient_id'), table_name='coordination_entries')
    op.drop_index(op.f('ix_coordination_entries_category'), table_name='coordination_entries')
    op.drop_table('coordination_entries')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_entities_user_id'), table_name='user_entities')
    op.drop_index(op.f('ix_user_entities_entity_id'), table_name='user_entities')
    op.drop_table('user_entities')
    op.drop_index(op.f('ix_user_availabilities_user_id'), table_name='user_availabilities')
    op.drop_index(op.f('ix_user_availabilities_entity_id'), table_name='user_availabilities')
    op.drop_index(op.f('ix_user_availabilities_day_of_week'), table_name='user_availabilities')
    op.drop_table('user_availabilities')
    op.drop_index(op.f('ix_subscription_usage_subscription_id'), table_name='subscription_usage')
    op.drop_table('subscription_usage')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_entity_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_entity_services_service_template_id'), table_name='entity_services')
    op.drop_index(op.f('ix_entity_services_entity_id'), table_name='entity_services')
    op.drop_table('entity_services')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_rpps'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_service_templates_required_profession_id'), table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_code'), table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_category'), table_name='service_templates')
    op.drop_table('service_templates')
    op.drop_table('roles')
    op.drop_table('professions')
    op.drop_table('countries')
    # ### end Alembic commands ###
